int counter = 0
bln pressed = false

use attr c12_door_fl -> frleftdoor
use attr c12_door_fr -> frrighdoor
use attr c12_door_rl -> releftdoor
use attr c12_door_rr -> rerighdoor
use attr speed -> speed
use attr license_plate -> lp

act update(obj context){
	flt mod = 0
	
    if(!pressed)
    	return
    ;;
    counter += 1;
	mod = counter % 20
	if(context.client && mod == 0)
		lp = speed * 2.5
	;;
    
    if(counter >= 100)
        counter = 0
    ;;
}

act interact(obj context){
    pressed = !pressed
    print(pressed)
    context.sync(pressed)
    return true
}
