int counter = 0
bln pressed = false

use attr c12_door_fl -> frleftdoor
use attr c12_door_fr -> frrighdoor
use attr c12_door_rl -> releftdoor
use attr c12_door_rr -> rerighdoor

act update(obj context){
    if(!pressed)
    	return
    ;;
    if(counter < 80)
    	counter += 1
    ;;
    else
        counter = 0
        //pressed = !pressed
        frleftdoor = false
    	frrighdoor = false
    	releftdoor = false
    	rerighdoor = false
    ;;
    //opening a door each second
    if(counter < 20){
    	frleftdoor.toggle()
    }
    else if(counter < 40){
    	frrighdoor.toggle()
    }
    else if(counter < 60){
    	releftdoor.toggle()
    }
    else if(counter < 80){
    	rerighdoor.toggle()
    }
}

act interact(obj context){
    pressed = !pressed
    print("Togging auto-doors!")
    print(pressed)
    return true
}
